### ISSUE TITLE
NPPN_DOCORDERCHANGED has wrong value

### ISSUE THREAD

**Issue by dail8859** [kbilsted/NotepadPlusPlusPluginPack.Net#1]
NPPN_DOCORDERCHANGED is defined [incorrectly](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/3e28c64b90309f13525c539355b6e77acce0195d/Demo%20Plugin/NppManagedPluginDemo/NppPluginNETHelper.cs#L631). It is an old bug from the original template. You might take a look at [this](https://github.com/sanastasiou/RTextNpp) plugin (this is where I first caught this bug) because this author has updated the C# code quite a bit that may be useful for this template.

**Comment by kbilsted** [comment]
Many thanks. I'm new to npp plugins myself ..

so any more specific hints for changes or pull request  will be much appreciated

**Comment by dail8859** [comment]
The notifications should be exactly the same as what is in the [Notepad++ source code](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/287ce9ec147d6d64224d8990f99385f57a240df4/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L546). You'll notice that there are also more messages that are not in the template. That's why I said it may just be easier to pull code from that repo I referenced. :)

**Comment by kbilsted** [comment]
fixed
