### ISSUE TITLE
Marshal.FreeHGlobal of NppTbData structure?

### ISSUE THREAD

**Issue by vinsworldcom** [kbilsted/NotepadPlusPlusPluginPack.Net#102]
Should there be a Marshal.FreeHGlobal() after:

https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/b588f001e5684afbe61af572fc95bff4d21e51b0/Visual%20Studio%20Project%20Template%20C%23/Main.cs#L98

`        Marshal.FreeHGlobal(_ptrNppTbData);`

as there is previously on line 55 for a similar allocation and point to structure usage:

https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/b588f001e5684afbe61af572fc95bff4d21e51b0/Visual%20Studio%20Project%20Template%20C%23/Main.cs#L52-L55

Cheers.

**Comment by rdipardo** [comment]
> Should there be a Marshal.FreeHGlobal() after:
> [ . . . ]
> ` Marshal.FreeHGlobal(_ptrNppTbData);`

In my (limited) experience with plugins that create docked windows, the allocated `TbData*` should really *not* be destroyed any sooner than the form that owns it. (At least that's the case with "unmanaged" languages [like Object Pascal].) A C# form can always [override #Dispose()] or [hook the `WM_DESTROY` message] and deallocate manually.

The risk of deallocating too soon is more apparent if your form is dark mode aware and gets redrawn with every theme change. If you've already trashed the pointer to the caption text, you'll see random bytes that look like nonsensical Chinese in the title bar.

> as there is previously on line 55

An icon handle is used only once, to [create a completely new object], so the source pointer can be cleaned up right away.

[like Object Pascal]: https://github.com/rdipardo/NPPFSIPlugin/commit/0909d50fd9ed7202ef437fb2266ceaff9463b11d
[override #Dispose()]: https://learn.microsoft.com/dotnet/standard/garbage-collection/implementing-dispose
[hook the `WM_DESTROY` message]: https://learn.microsoft.com/dotnet/api/system.windows.forms.control.wndproc?view=windowsdesktop-7.0
[create a completely new object]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/11f7ba2e0a80dae890c5162a92635d6c6151af64/PowerEditor/src/WinControls/ToolBar/ToolBar.cpp#L466
