### ISSUE TITLE
PluginPack doesn't work

### ISSUE THREAD

**Issue by LexaGV** [kbilsted/NotepadPlusPlusPluginPack.Net#113]
I compiled demo plugin on Win7x64 (for x64 Notepad++ v8.4.4), run N++ under VS and... nothing!
1. Compilation of demo does NOT copy result DLL into /plugins/; I made it manually
2. Not sure, but looks like Pack is outdated - maybe it misses some init stage? I checked EVERYTHING - toolbar, menu, but plugin does not appear anywhere.
3. I checked another plugin https://github.com/kbilsted/NppPluginGuidHelper - it was a bit outdated, but I fixed code (mostly in bare plugin code), but again didn't find ANY mention of that plugin inside N++

Request for author: can you please check, maybe smth is changed in N++ API? Also there is not a single word which DLLs should be inside /plugins/ - I copied only plugin DLL itself and it doesn't work.

**Comment by mahee96** [comment]
was the issue resolved? why was it closed without comment or resolution
