### ISSUE TITLE
Code generate notepad++ constants and helper methods

### ISSUE THREAD

**Issue by kbilsted** [kbilsted/NotepadPlusPlusPluginPack.Net#13]
Today we hand-synchronize https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/master/Visual%20Studio%20Project%20Template%20C%23/Integration/Msgs_h.cs   with https://github.com/notepad-plus-plus/notepad-plus-plus/blob/287ce9ec147d6d64224d8990f99385f57a240df4/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h

I suggest we build a parser and code generate the file like we do with the tools located in https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/tree/master/ToolsForMaintainersOfTheProjectTemplate/Scintilla_iface_synchronizer

**Comment by kbilsted** [comment]
@dail8859  something for you? :)

**Comment by dail8859** [comment]
I do agree automating it would be nice have, but I'll pass for now. It seems the effort to implement it doesn't really justify the value gained. The file really doesn't change [very often](https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h), plus if updates are made to the header there's nothing to say that it wouldn't break whatever script was used to parse it.

**Comment by kbilsted** [comment]
@dail8859  no worries mate ;) I'm not sure its not worth the gain as it can also generate all the methods that we have generated here https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/2cdeeb927baed3788606bc86ec6176004a0dcf0e/Visual%20Studio%20Project%20Template%20C%23/ScintillaGateway.cs   that file is 5000 lines long and we have an interface file of 2500 lines also code generated

**Comment by dail8859** [comment]
Oh I completely agree it is needed for the Scintilla methods. The iface file Scintilla provides gives adequate information to generate all those methods. If Notepad++ also provided a similar iface file then it would make it much easier and be worth it.

Just trying to pull information out of the header would be much more of a pain and there really is no guarantee of formatting, validity, etc. Instead of scripting something, it would probably take the same amount of time to use some regexs and brute force to create the Msgs_h.cs file once and then just hand edit it every now and then.

I've always hated the inconsistencies in the Notepad++ API :)

**Comment by kbilsted** [comment]
Perhaps a better strategy then is to create a  consistent layer on top of
n++ :) you can create it as a generic file and we can then generate c++ and
c# for it :)
Den 4. maj 2016 7.52 PM skrev "dail8859" <notifications@github.com>:

**Comment by dail8859** [comment]
Which is exactly what the iface file is from Scintilla. :) Notepad++ isn't as consistent as Scintilla is with its API but I guess it is still possible.

So its a matter of either (a) maintaining a script to try to parse out the header manually, or (b) maintain an iface file that at least has the added benefit of being useful to other languages/programmers/maintainers.

**Comment by kbilsted** [comment]
Or convince mr ho to use it :)
Den 4. maj 2016 8.56 PM skrev "dail8859" <notifications@github.com>:

**Comment by kbilsted** [comment]
I've created a file synchronizer NotepadPlusPlusPluginPack.Net\ToolsForMaintainersOfTheProjectTemplate\notepad_hfiles_synchronizer`
