### ISSUE TITLE
 Export Failed?

### ISSUE THREAD

**Issue by LeSou** [kbilsted/NotepadPlusPlusPluginPack.Net#14]
```
[DllExport(CallingConvention=CallingConvention.Cdecl)]
        static bool isUnicode()
        {
            return true;
        }

        [DllExport(CallingConvention = CallingConvention.Cdecl)]
        static void setInfo(NppData notepadPlusData)
        {
            PluginBase.nppData = notepadPlusData;
			Main.CommandMenuInit();
        }

        [DllExport(CallingConvention = CallingConvention.Cdecl)]
        static IntPtr getFuncsArray(ref int nbF)
        {
            nbF = PluginBase._funcItems.Items.Count;
            return PluginBase._funcItems.NativePointer;
        }

        [DllExport(CallingConvention = CallingConvention.Cdecl)]
        static uint messageProc(uint Message, IntPtr wParam, IntPtr lParam)
        {
            return 1;
        }

        static IntPtr _ptrPluginName = IntPtr.Zero;
        [DllExport(CallingConvention = CallingConvention.Cdecl)]
        static IntPtr getName()
        {
            if (_ptrPluginName == IntPtr.Zero)
                _ptrPluginName = Marshal.StringToHGlobalUni(Main.PluginName);
            return _ptrPluginName;
        }

        [DllExport(CallingConvention = CallingConvention.Cdecl)]
        static void beNotified(IntPtr notifyCode)
        {
            SCNotification nc = (SCNotification)Marshal.PtrToStructure(notifyCode, typeof(SCNotification));
            if (nc.nmhdr.code == (uint)NppMsg.NPPN_TBMODIFICATION)
            {
                PluginBase._funcItems.RefreshItems();
                Main.SetToolBarIcon();
            }
            else if (nc.nmhdr.code == (uint)NppMsg.NPPN_SHUTDOWN)
            {
                Main.PluginCleanUp();
                Marshal.FreeHGlobal(_ptrPluginName);
            }
        }
```
```
>dumpbin -exports MyNppPlugin1.dll
Microsoft (R) COFF/PE Dumper Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file MyNppPlugin1.dll

File Type: DLL

  Section contains the following exports for \MyNppPlugin1.dll

    00000000 characteristics
    57314652 time date stamp Tue May 10 10:24:18 2016
        0.00 version
           0 ordinal base
           3 number of functions
           3 number of names

    ordinal hint RVA      name

          2    0 000125AE getFuncsArray
          4    1 CFFFE303 getName
          0    2 0001259E isUnicode

  Summary

        2000 .reloc
        2000 .rsrc
        2000 .sdata
       12000 .text
```

Visual Studio 2015   windows10 

I erroneous operation yet ?

**Comment by kbilsted** [comment]
any warnings or error messages when you build?

**Comment by LeSou** [comment]
1>  NppManagedPluginDemo.VS2015 -> E:\Code\NotepadPlusPlusPluginPack\Demo Plugin\NppManagedPluginDemo\bin\Debug\Demo.dll
1>  ILDasm: calling 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\ildasm.exe' with /quoteallnames /unicode /nobar /linenum "/out:C:\Users\LC\AppData\Local\Temp\tmp2F06\Demo.il" "E:\Code\NotepadPlusPlusPluginPack\Demo Plugin\NppManagedPluginDemo\bin\Debug\Demo.dll"
1>  ILDasm: ildasm 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\ildasm.exe' returned gracefully.
1>  ILAsm: calling 'C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\ILAsm.exe' with /nologo "/out:E:\Code\NotepadPlusPlusPluginPack\Demo Plugin\NppManagedPluginDemo\bin\Debug\Demo.dll" "C:\Users\LC\AppData\Local\Temp\tmp2F06\Demo.il" /DLL "/resource=C:\Users\LC\AppData\Local\Temp\tmp2F06\Demo.res"  /debug  
1>  ILAsm: ILAsm 'C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\ILAsm.exe' returned gracefully.
1>  ILAsm: calling 'C:\Tools\VS2015\VC\bin\Lib.exe' with "/def:E:\Code\NotepadPlusPlusPluginPack\Demo Plugin\NppManagedPluginDemo\bin\Debug\Demo.X86.def" /machine:X86 "/out:E:\Code\NotepadPlusPlusPluginPack\Demo Plugin\NppManagedPluginDemo\bin\Debug\Demo.lib"
1>  ILAsm: Lib 'C:\Tools\VS2015\VC\bin\Lib.exe' returned gracefully.

**Comment by LeSou** [comment]
No abnormalities or warnings ?

**Comment by kbilsted** [comment]
I will have a look at the dll's I'm producing at home to check for differences.

**Comment by LeSou** [comment]
Thank you. Waiting for your reply

**Comment by kbilsted** [comment]
I just tried my demo plugin from branch https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/tree/topic/editorgateway_v1 soon I'll be merging this branch and create a new release. Please try it out.

here is the output

	PS C:\src\NotepadPlusPlusPluginPack.Net\Demo Plugin\NppManagedPluginDemo\bin\Debug> & 'C:\Program Files (x86)\Microsoft
	Visual Studio 14.0\VC\bin\dumpbin.exe' -exports .\Demo.dll
	Microsoft (R) COFF/PE Dumper Version 14.00.23918.0
	Copyright (C) Microsoft Corporation.  All rights reserved.


	Dump of file .\Demo.dll

	File Type: DLL

	  Section contains the following exports for \Demo.dll

		00000000 characteristics
		572B1CF6 time date stamp Thu May  5 12:14:14 2016
			0.00 version
			   0 ordinal base
			   6 number of functions
			   6 number of names

		ordinal hint RVA      name

			  5    0 0001691E beNotified
			  2    1 000168EE getFuncsArray
			  4    2 0001690E getName
			  0    3 000168CE isUnicode
			  3    4 000168FE messageProc
			  1    5 000168DE setInfo

	  Summary

			2000 .reloc
			2000 .rsrc
			2000 .sdata
		   16000 .text

**Comment by kbilsted** [comment]
I just updatede the code - try the script `makerelease.ps1` on branch https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/tree/topic/editorgateway_v1  and create a new plugin in visual studio

**Comment by LeSou** [comment]
Dump of file MyNppPlugin3.dll

File Type: DLL

  Section contains the following exports for \MyNppPlugin3.dll

    00000000 characteristics
    57327D36 time date stamp Wed May 11 08:30:46 2016
        0.00 version
           0 ordinal base
           3 number of functions
           3 number of names

    ordinal hint RVA      name

          2    0 0002607E getFuncsArray
          4    1 9D6F942E getName
          0    2 0002606E isUnicode

  Summary

        2000 .reloc
        2000 .rsrc
        2000 .sdata
       26000 .text

Thank you , I tested is not enough,This is what causes ?

**Comment by kbilsted** [comment]
I honestly do not know. Maybe people on https://notepad-plus-plus.org/community/category/5/plugin-development can help..

**Comment by LeSou** [comment]
Okay, thank you

**Comment by kbilsted** [comment]
Do you have c++ installed via the visual studio installer?

**Comment by kbilsted** [comment]
@LeSou  try sending me the source code and i'll have a look - you may not be the only one with this problem..

**Comment by Jddl** [comment]
I switched the system environment to English, it worked~

**Comment by kbilsted** [comment]
Thanks for the feedback. What do you mean English environment ?

**Comment by Jddl** [comment]
Override for Windows display language.
