### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by AdrianHHH** [kbilsted/NotepadPlusPlusPluginPack.Net#16]
Hello Kasper,

This is a slightly modified copy of the issue first posted [here](https://notepad-plus-plus.org/community/topic/11992/update-pluginpack-updated-to-v0-92-76).

I have not made any progress on understanding the issues. When I have a better understanding of how to use the plugin pack I would be happy to make some improvements to the ReadMe etc.

Thank you for creating the new plugin pack. Unfortunately I am having some challenges in using it and I would welcome your comments on what I am doing wrong.

First a minor observation on the installation notes. In the "README.md" file at section “Getting started” 2: When we copy the NppPlugin[version].zip file should we keep the version number in the file name or should we rename it to NppPlugin.zip? I just copied the file and kept the version number, that seemed to work.

I created a new project using the template. It defaults to .NET 3.5.2 which is not on my computer, so I changed the project to target 4.6.1.

Tried to build the project without making any changes and without adding any of the code of my plugin. Get two errors:

```
1>[[...]]\Main.cs(19,31,19,41): error CS0103: The name 'Properties' does not exist in the current context
1>[[...]]\Main.cs(20,37,20,47): error CS0103: The name 'Properties' does not exist in the current context
```

against these two lines:

```
    static Bitmap tbBmp = Properties.Resources.star;
    static Bitmap tbBmp_tbTab = Properties.Resources.star_bmp;
```

File “Main.cs” has the line “namespace Kbg.NppPluginNET” (for class Main). Comparing to the Demo project, file “Demo.cs” has the line “namespace Kbg.Demo.Namespace” and in the demo project file “Resources.Designer.cs” has the line “namespace Kbg.Demo.Namespace.Properties”.

In my project I changed the namespace names in files “UnmanagedExports.cs” and “Resources.Designer.cs” to match my project. Also I added a “using Kbg.NppPluginNET;” to file “Main.cs” so that “frmMyDlg” in the line “static frmMyDlg frmMyDlg = null;” is available.

It would be useful if the installation notes could give some guidance on which files and classes should use which namespaces.

Building the solution gives the error (was all on one line, so manually wrapped):

```
1>[[...]]\PluginInfrastructure\DllExport\NppPlugin.DllExport.targets(8,5): error MSB4062:
The "NppPlugin.DllExport.MSBuild.DllExportTask" task could not be loaded from the assembly [[...]]\PluginInfrastructure\DllExport\NppPlugin.DllExport.MSBuild.dll.
Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The system cannot find the file specified.
Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

I find this message from Visual Studio very confusing. The text “UsingTask” does not seem to be in any of the files in the solution, nor can I find “Microsoft.Build.Utilities” or “ITask”.

Next I installed .NET 3.5.2 and then the build does not report the above error. Now the build fail with the message:

```
1>AfterBuild:
1>  Cannot find lib.exe in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\..\..\VC\bin'.
```

There is no “lib.exe” in any of the sub-directories of “Microsoft Visual Studio 14.0” on my computer, but there are versions in the correct sub-directories of both “Microsoft Visual Studio 11.0” and “Microsoft Visual Studio 12.0”.

I also tried building the demo project and it also fails to find “lib.exe”.

Environment is Windows 10 with Microsoft Visual Studio Enterprise 2015 Version 14.0.25123.00 Update 2.

Regards
 Adrian

**Comment by kbilsted** [comment]
Hi @AdrianHHH 

thanks for the report. I hope the following points are of use. Feel free to improve the readme and other stuff. It sure would be great to get rid of the 3.5.2 dependency eg. but it requires digging around, uninstalling stuff or maybe setting up a virtual machine.. not something I have in scope at the moment.

  * keeping the version number is fine - we should change the readme
  * NET 3.5.2  is not an requirement - we should change the readme to say whatever version above is fine too
  * just did a new project which was buiding fine on my machine. and the two images are available when i click the resources.resx and they are found as files in my properties folder. Not sure what is wrong
  * changing the namespace of `PluginInfrastructure\DllExport\DllExportAttribute.cs` should be the only one that you should not change - we should change the readme
  * `"NppPlugin.DllExport.MSBuild.DllExportTask" task could not be loaded from the assembly` sounds really bad. Not sure what has changed in C# 4 - the assembly re-write parts of the codebase is still new to me so maybe stackoverflow is a good starting point. For the time being it looks as though we should have a separate issue for removing the dependency on C# v3.5.2  - and update the readme to say you need to install it (and a link to this new issue)
  * There is no “lib.exe” in any of the sub-directories of “Microsoft Visual Studio 14.0” on my computer, but there are versions in the correct sub-directories of both “Microsoft Visual Studio 11.0” and “Microsoft Visual Studio 12.0”. **
    * I dont know the logic visual studio installations. I have a feeling that the lib.exe is tied to the c++ installation that is required.
    * the readme should be updated telling you to edit the file `\PluginInfrastructure\DllExport\NppPlugin.DllExport.targets` on the lines `LibToolPath="$(DevEnvDir)\..\..\VC\bin"` and `LibToolDllPath="$(DevEnvDir)"` and replace `$(DevEnvDir)` with whereever users locate their `lib.exe` - personally I only have a copy in my vs v14.0 folder.

feel free to ask again

**Comment by AdrianHHH** [comment]
Thank you for the comments Kasper. I have made some progress.

- File "lib.exe" is only installed as part of the C/C++ tools, I had not installed them. This stage now works.

- The `<Copy...>` part of file ""NppPlugin.DllExport.targets" tries to write the plugin DLL into "C:\Program Files (x86)\Notepad++\plugins\", which requires administrator permissions or similar. I installed Notepad++ to allow plugins to be loaded from APPDATA. So I changed one line of the `Copy` block to be as follows (I am not sure what the `Condition=...` achieves so I left it alone):

    `DestinationFolder="$(APPDATA)\Notepad++\plugins\"`

This was done on a new project with minimal changes made, I just wanted to go through th build process. Now I can start to move my code into the plugin template.

**Comment by kbilsted** [comment]
Im glad to hear it works. FEel free to update the readme so thing become clearer for the next person to use this lib :)

**Comment by silver-graf** [comment]
hello, AdrianHHH.

**Comment by kbilsted** [comment]
@silver-graf try posting the code to github..

**Comment by acrolink** [comment]
@kbilsted I am getting the same error `this ansi plugin is not compatible with your unicode notepad++` even with the very basic template (untouched).

**Comment by kbilsted** [comment]
* what version of .net, how many bits
* what version of n++, how many bits

**Comment by acrolink** [comment]
@kbilsted 

n++ latest available 32 bit, net 4.6.1, plug-in compiled to 32 arch. 

I see the problem only when compiling inside VS 2017, when compiling using VS 2015 no issue whatsoever, plug-in loads and works fine.

**Comment by nebosite** [comment]
I'm stuck trying to get this to work on VS 2022.  Anyone have a working demo project they can point me to?

**Comment by mahee96** [comment]
Whats your issue
