### ISSUE TITLE
X64 pointer arithmetic issue

### ISSUE THREAD

**Issue by chcg** [kbilsted/NotepadPlusPlusPluginPack.Net#18]
See https://notepad-plus-plus.org/community/topic/12633/npppluginnet-64-bit.

Issue is caused by problematic pointer arithmetic in

    public void Add(FuncItem funcItem)
and

    public void RefreshItems()

in class FuncItems in NppPluginNETHelper.cs, like:

        IntPtr ptrPosNewItem = (IntPtr)((int)newPointer + oldSize);

So the cast to int from type IntPtr shortens the pointer for X64, see e.g.

https://blogs.msdn.microsoft.com/jaredpar/2008/11/11/properly-incrementing-an-intptr/
or
https://stackoverflow.com/questions/1866236/add-offset-to-intptr

**Comment by kbilsted** [comment]
Closed by pr
