### ISSUE TITLE
(old) plugin version 0.7

### ISSUE THREAD

**Issue by ufo** [kbilsted/NotepadPlusPlusPluginPack.Net#2]
Hi,
there was a more recent version over here, in case you missed it and want to have a look at anything in it:
https://bitbucket.org/uph0/npppluginnet
But please keep on pushing your template version, since I'm too busy in real life anyway.
Thanks!

**Comment by kbilsted** [comment]
oh I didn't realise. Thanks! I'll have a look at it. Mostly what I've done is to connect the demo to softlinking with the template files and removing the partial classes. I was wondering if the template should only do the dllexport and then have a nuget for all the actual integration code instead. That way people can easier upgrade their plugin code...

**Comment by kbilsted** [comment]
@ufo  I see that the file `NppPlugin.NET.v0.7\Demo\NppManagedPluginDemo\DllExport\NppPlugin.DllExport.targets`  has changed content. Can you elaborate a bit on that

Also the files `Mono.Cecil.dll`, `NppPlugin.DllExport.dll`, `NppPlugin.DllExport.MSBuild.dll` have changed. Is there a reason you are not depending on these files through Nuget?
