### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by kbilsted** [kbilsted/NotepadPlusPlusPluginPack.Net#21]
A lot of good thoughts here on the 64bit issue. Maybe some one will fixup this in here

https://notepad-plus-plus.org/community/topic/12633/npppluginnet-64-bit

**Comment by kbilsted** [comment]
@lipnitsk  have you had any luck with the 64 bit stuff? see #30

**Comment by SkorkaJ** [comment]
Hello, 

the class ClikeStringArray cause an overflow on Win10 64bit. 
The constructor “ClikeStringArray(int num, int stringCapacity)” of the class create the trouble.
For 64bit the `IntPtr _nativeArray` should be casted to long

OLD code
`Marshal.WriteIntPtr((IntPtr)((int)_nativeArray + (i * IntPtr.Size)), item);`
`Marshal.WriteIntPtr((IntPtr)((int)_nativeArray + (num * IntPtr.Size)), IntPtr.Zero);`

New Code
` Marshal.WriteIntPtr((IntPtr)((long)_nativeArray + (i * IntPtr.Size)), item);`
`Marshal.WriteIntPtr((IntPtr)((long)_nativeArray + (num * IntPtr.Size)), IntPtr.Zero);`

This solved the problem for me. 

Thanks
SkorkaJ

**Comment by chcg** [comment]
See also https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/pull/35#issuecomment-357644668 regarding ClikeStringArray issues.
