### ISSUE TITLE
Q: Adding 3rd Party Libs via NuGet and using them

### ISSUE THREAD

**Issue by nea** [kbilsted/NotepadPlusPlusPluginPack.Net#23]
Hi there

First of all: Thanks a lot for this template! Getting it to work was simple and as expected. Thanks for that.

But I have a question regarding the addition of other 3rd Party Libraries: Do these have to be "prepared" to be usable as extended plugin library? Or do these have to be added in some way I am missing, when referenced via NuGet?

Just for example: https://github.com/Knagis/CommonMark.NET
Using it results in instant errors. Calling static string/text variables is no problem, so I think it is available. But using it results in errors I cannot event catch, and as I used it for testing purposes in the notification method, Notepad++ doesn't even boot but crashes with a dialog without much info, just the message.

Thanks a lot in advance for any help and sorry if this question is too primitive ^^#

**Comment by kbilsted** [comment]
Perhaps it has to do with dynamically loading. Perhaps you can il-merge your dependency so that it's all in one dll. ? Do let me know if you get it working

**Comment by nea** [comment]
Hi there

Thanks for the direction.

I tried to use ILMerge and the MSBuild Task with Markdig and it wouldn't work. The process crashes with an "syntax error at aggressiveinlining" already. 
I switch to CommonMark.net then, which builds fine and I would get a compiled .dll in Notepad++. But as soon as I open NPP it states that the .dll is incompatible and cannot be used.

What I did was using this template, building a new project and just calling one method in the library from the 'OnNotification' method. Without ILMerge NPP crashes with an error.

If you like to try, the only thing I do is
* creating a project with your template
* adding the reference to Markdig or CommonMark.net via NuGet
* adding the following to the OnNotification method

`
            if(notification.Header.Code == (uint)SciMsg.SCN_CHARADDED) {
                if(frmMyDlg != null) {
                    try {
                        var result = CommonMark.CommonMarkConverter.Convert("**Hello world!**");
                    } catch(Exception) {
                    }
                }
            }
`

This alone is enough to crash it or to break what I am doing with ILMerge to be incompatible. Something dynamically, as you stated, I am probably doing wrong, but missing the correct way.


Sorry

**Comment by kbilsted** [comment]
To ensure it has to do with the loading of code, try inlining your dependency as code in your project..ie clone the other repo and copy all files to your repo. Then see if you can make it work when you build everything in one go.

**Comment by nea** [comment]
Hey

I cloned the base code from https://github.com/Knagis/CommonMark.NET into a newly created template and made the same call and it works.

**Comment by kbilsted** [comment]
Great. Perhaps asking in https://notepad-plus-plus.org/community/category/5/plugin-development

**Comment by kbilsted** [comment]
ILMerge or cloning directly seems to be working. I'll close this and open an issue for documentation in the `README`
