### ISSUE TITLE
Cannot get C# plugins to run with x64 NPP for anything newer than Windows 7 x64 OS

### ISSUE THREAD

**Issue by MattWorkWeb** [kbilsted/NotepadPlusPlusPluginPack.Net#30]
I've tried the older c# template and the newer and cannot get to run on Windows 8.1 or Windows 10 using x64 bit version of NPP.  Has anyone had luck with this and if so where can I get the template?  They work for x64 on Windows 7 and x86 on all OS's.  I get plugin dll won't load with current version of NPP message at NPP launch.  Any thoughts?

**Comment by ewwink** [comment]
switch target framework to .net 4.0 solve the problem.

**Comment by kbilsted** [comment]
try the v0.94.00 release
