### ISSUE TITLE
Build FAILED (Done executing task "DllExportTask" -- FAILED.)

### ISSUE THREAD

**Issue by UniChen** [kbilsted/NotepadPlusPlusPluginPack.Net#32]
Excuse me. I got the problem of build, how can I solve it?
I follow the "Getting started" that from the README.md and create a new notepad++ template project.
finally, I just build this project but got the problem below.

1>  ILAsm: calling 'D:\Tool\Visual Studio 2015\VC\bin\Lib.exe' with "/def:D:\SourceCode\C#\IntelHexViewer\IntelHexViewer\bin\Debug\IntelHexViewer.X86.def" /machine:X86 "/out:D:\SourceCode\C#\IntelHexViewer\IntelHexViewer\bin\Debug\IntelHexViewer.lib" (TaskId:42)
1>  ILAsm: Lib 'D:\Tool\Visual Studio 2015\VC\bin\Lib.exe' returned gracefully. (TaskId:42)
1>D:\SourceCode\C#\IntelHexViewer\IntelHexViewer\PluginInfrastructure\DllExport\NppPlugin.DllExport.targets(8,5): error : 
1>     at NppPlugin.DllExport.Parsing.IlParser.RunILTool(String installPath, String toolFileName, String requiredPaths, String workingDirectory, String settingsName, String arguments, String toolLoggingCode, String verboseLoggingCode, DllExportNotifier notifier, Int32 timeout)
1>     at NppPlugin.DllExport.Parsing.ILAsm.RunLibTool(CpuPlatform cpu, String directory, String defFileName)
1>     at NppPlugin.DllExport.Parsing.ILAsm.RunCore(CpuPlatform cpu, String fileName, String ressourceParam, String ilSuffix)
1>     at NppPlugin.DllExport.Parsing.ILAsm.Run(String outputFile, String ilSuffix, CpuPlatform cpu)
1>     at NppPlugin.DllExport.Parsing.ILAsm.ReassembleFile(String outputFile, String ilSuffix, CpuPlatform cpu)
1>     at NppPlugin.DllExport.DllExportWeaver.RunILAsm(ILAsm ilAsm)
1>     at NppPlugin.DllExport.DllExportWeaver.Run()
1>     at NppPlugin.DllExport.MSBuild.DllExportTask.Execute() (TaskId:42)
1>Done executing task "DllExportTask" -- FAILED. (TaskId:42)

**Comment by kbilsted** [comment]
x86 or x64 build?

**Comment by kbilsted** [comment]
not heard back
