### ISSUE TITLE
ScintillaGateway GetText truncate

### ISSUE THREAD

**Issue by timop18** [kbilsted/NotepadPlusPlusPluginPack.Net#42]
Hi,

I've got a problem with the GetText(int length) method in the ScintillaGateway.
I wish to get a big text (around 15kb or even more), in that case the result is truncated at 10kb.
This is because of the textBuffer size.
Is it possible to replace original code :
`byte[] textBuffer = new byte[10000];`
with
`byte[] textBuffer = new byte[length];`

Thank you

Timop

**Comment by jokedst** [comment]
There is a fix in pull request #38 but it hasn't been merged for a long while now...

**Comment by timop18** [comment]
Ah yes, thank you jokedst, I missed this request...
