### ISSUE TITLE
Copy the dll in the plugin subdirectory

### ISSUE THREAD

**Issue by BlaxOne** [kbilsted/NotepadPlusPlusPluginPack.Net#45]
Hello,

I followed the steps to install and build your C# NppPlugin package. All went fine, except that the plugin was not showing in the plugin menu, nor the plugin icon in the toolbar. I found the dll had been copied directly in the plugins directory of Notepad++. I also noticed that the dlls of all the other plugins were placed in their own subdirectories. So I created a directory (in the plugins directory of Notepad++) that I named with the plugin's name, and I put the dll in this new directory. I restarted Notepad++ and the plugin was present in the plugins menu and worked as expected.

Now I would like to be able to tell Visual Studio to copy the dll in that subdirectory, so that I don't have to do it manually after each build. I looked in project properties > build and > post-build events, but I found nothing set about copying the dll elsewhere than in the VS project output directory (in my case: bin\Debug-x64\)...

-- Using NppPlugin0.94.00.zip, Visual Studio 2017 (target Framework: .Net Framework 4, platform target: x64), and Notepad++ v7.6.3 64-bit (which moved "plugins home from %ProgramData% to %ProgramFiles% for the sake of security").

Any help appreciated.

**Comment by jokedst** [comment]
Actually the pull request #44 does exactly that. Apply it yourself and it should work.

**Comment by BlaxOne** [comment]
It works. Thanks a lot.

**Comment by kbilsted** [comment]
#44 will be merged soon - closing
