### ISSUE TITLE
The ANSI plugin is not compatible with your UNICODE Notepad++

### ISSUE THREAD

**Issue by gandarez** [kbilsted/NotepadPlusPlusPluginPack.Net#47]
OS: Windows 10 Pro x64 | Version 1803 | Build 17134.648
Notepad++: v7.5.9 x64

Always I compile using x64 platform I get an error when running np++
![image](https://user-images.githubusercontent.com/782854/55803599-0f111600-5ab1-11e9-82a1-6b4244e82d9c.png)

![image](https://user-images.githubusercontent.com/782854/55803649-24864000-5ab1-11e9-95d3-3635320ae797.png)

**Comment by kbilsted** [comment]
Does it work with an older version of notepad?
Does it work in 32bit?
maybe there are hints here https://github.com/oleg-shilo/cs-script.npp/issues/28

**Comment by kbilsted** [comment]
What was the problem @gandarez

**Comment by gandarez** [comment]
I just updated to v0.94.00 and it worked

**Comment by kbilsted** [comment]
Many thanks for for getting back to me.

**Comment by gandarez** [comment]
Hi it started happening again. I tried updating all files under `PluginInfrastructure` as a tentative to solve the problem. Both platforms are throwing the message of incompatible ANSI.

OS: Windows 10 Pro x64 
Notepad++: v7.9 x64

**Comment by gandarez** [comment]
I just realized that building with VS 2019 caused the error. I had to get back to VS 2017. Interesting point to be investigated.
