### ISSUE TITLE
0.94-ansi plugin is not compatible with your unicode notepad++

### ISSUE THREAD

**Issue by joylin1984** [kbilsted/NotepadPlusPlusPluginPack.Net#52]
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : D:\Program Files\NPP\mynpp.7.6.6.bin.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 10 (64-bit) 1607
NotepadPlusPlusPluginPack.Net：0.94.00
VS2015 up3 include C++

when npp loading dll , has error as "ansi plugin is not compatible with your unicode notepad++"

[MyNppPlugin2.zip](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/files/3717999/MyNppPlugin2.zip)

[MyNppPlugin2_bin_x64.zip](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/files/3718005/MyNppPlugin2_bin_x64.zip)

**Comment by gurikbal** [comment]
[NppPlugin0.93.96.zip](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/releases/download/0.93.96/NppPlugin0.93.96.zip) is for Unicode build

**Comment by mahee96** [comment]
@joylin1984 @kbilsted With latest release NppPlugin0.94.00.zip this issue is not reproducible. I used the downloaded template in VS2019 and in x64 build, the Notepad++ application just works fine with my dummy test plugin.

**Comment by gurikbal** [comment]
keep `namespace Kbg.NppPluginNET` then try it.

**Comment by mahee96** [comment]
@gurikbal are you referring to main.cs of the plugin where I need to have this namespace to reproduce this error? I am not sure, could you be more specific? (I tried again with a fresh download of jan 2018 release). I can run the dummy plugin fine in Notepad++ x64 (v 7.8.9) on Win 10 x64 Enterprise with that namespace which comes (default) out of box(from downloaded template). For debugging and build I am using VS2019 and you can see that I don't have any exceptions thrown in the debug console too.

Attaching some screenshots:

![uses_default_namespace_which_comes_from_template](https://user-images.githubusercontent.com/47920326/88889630-07edb880-d25e-11ea-9450-c82a2e88d80e.JPG)
<img width="960" alt="Plugin_works_and_is_debuggable" src="https://user-images.githubusercontent.com/47920326/88889635-0ae8a900-d25e-11ea-8887-1e716ce22ea9.png">

**Comment by gurikbal** [comment]
[Kbg.NppPluginNET.zip](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/files/5002034/Kbg.NppPluginNET.zip)


![capture-20200730-202553](https://user-images.githubusercontent.com/36083297/88939036-ad774b00-d2a3-11ea-845f-49a2e32a73cc.png)

**Comment by mahee96** [comment]
@gurikbal Thanks for getting back to my request, I tried to unzip your project and opened it up in VS2019 which i am using.

First thing I observed, directly clicking on build without any changes (solution had x64 and Release mode set as default upon opening), caused a build failure with message "**Build Failed**" on the output window. [**No warnings, No Errors**, 21 Info messages]
But it still gave me an assembly in the output path "$(SolutionDir)\NPP regular expression tutorial\bin\x64\Release\Kbg.NppPluginNET.dll". 
I manually copied this DLL into Notepad++ plugin directory under folder "..\plugins\Kbg.NppPluginNET\Kbg.NppPluginNET.dll" and when I started my Notepad++ x64 application **_I received the error message "ANSI plugin not compatible...."_**.

So to resolve the build failure first, _I found similar issue and to **enable "detailed" build messages** to know exactly what went wrong with the build._ ref: https://github.com/versionone/VersionOne.Client.VisualStudio/issues/10

After changing to detailed build messages, I can see from the build output,

1>Task "DllExportTask"
1>  **Cannot find lib.exe in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\..\..\VC\bin'.**
1>**Done executing task "DllExportTask" -- FAILED.**
1>Done building target "AfterBuild" in project "NPP regular expression tutorial.csproj" -- FAILED.
1>
1>**Build FAILED.**
1>    **0 Warning(s)**
1>    **0 Error(s)**
1>
1>Time Elapsed 00:00:00.68
========== Rebuild All: 0 succeeded, **1 failed,** 0 skipped ==========

So I **_checked your NppPlugin.DllExport.targets file_** present in "Kbg.NppPluginNET\NPP regular expression tutorial\PluginInfrastructure\DllExport\" directory and **_it was outdated_**.

The **_lib.exe missing/not found_** issue was **_already addressed_** by using a conditional target exports property **_in the commit_** https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/commit/d000f005220b7adb8863dfc77770cf48aee5f19d#diff-cf93b2d72884eed7d8f6d4e4af1456cd on 14-Jan-2018 and when I checked my template, _I was using the latest one with the fix_ **_[release NppPlugin0.94.00.zip has this fix, 21-Jan-2018]_**
So I simply replaced that file and re-opened your solution and clicked on build for x64 release target.

This time "**Build Succeeded**", and the latest _NppPlugin.DllExport.targets_ file correctly places the plugin into Notepad++ plugins directory.

**Notepad++ started fine and the plugin was installed which I was able to use.**

Let me know if this resolves your issue :)

I have attached the screenshot and the updated zip (renamed the old file to "NppPlugin.DllExport.targets.bak" and added in,  the updated file).

[[Tested]Kbg.NppPluginNET.zip](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/files/5003040/Tested.Kbg.NppPluginNET.zip)

<img width="960" alt="Working_plugin" src="https://user-images.githubusercontent.com/47920326/88958492-2b485000-d2be-11ea-91db-714064137b64.png">

**Comment by gurikbal** [comment]
no no

**Comment by mahee96** [comment]
The ANSI code issue in the plugin has been resolved in the latest master branch, a release might be required to have a new package. 

Until then,

Please directly download the source, run the "makerelease.ps1" powershell script to zip the template and place it into VS2019 Templates folder. From there, you can see the latest template when you launch Visual Studio new project page.
