### ISSUE TITLE
Location of plugin dll in Notepad++ after build not in appropriate location

### ISSUE THREAD

**Issue by hatcherj** [kbilsted/NotepadPlusPlusPluginPack.Net#53]
NPP Version 7.7.1 (64-bit)
If I create a new project called XXX and build, it will put a dll in C:\Program Files\Notepad++\plugins called XXX.dll

In this version of NPP the dll needs to go in a folder of the exact same name so in this location: C:\Program Files\Notepad++\plugins\XXX\XXX.dll

----------------------------
To get around this for now in C:\Program Files\Notepad++\plugins I created a folder with the same name as my dll (in the above example XXX)
then I edited the file in my project called NppPlugin.DllExport.targets from this...
`<Copy 
        SourceFiles="$(TargetPath)" 
        DestinationFolder="$(ProgramW6432)\Notepad++\plugins\" 
        Condition="Exists('$(ProgramW6432)\Notepad++\plugins\') AND '$(Platform)'=='x64'"
        ContinueOnError="false" />`

to...
`<Copy 
        SourceFiles="$(TargetPath)" 
        DestinationFolder="$(ProgramW6432)\Notepad++\plugins\$(ProjectName)\" 
        Condition="Exists('$(ProgramW6432)\Notepad++\plugins\$(ProjectName)\') AND '$(Platform)'=='x64'"
        ContinueOnError="false" />`

this is only a temporary fix.  The build would need to create the folder if it did not exist

Link to forum discussion:  https://stackoverflow.com/questions/40015350/how-to-install-a-notepad-plugin-offline

**Comment by kbilsted** [comment]
Thanks for the feedback. PR is welcome

**Comment by mahee96** [comment]
@kbilsted This issue is now resolved in the following commit and has been already integrated into the master branch  ref: https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/commit/7f3d568e39d07986d237313fb12b8771e5118e70#diff-cf93b2d72884eed7d8f6d4e4af1456cd

The last release(NppPlugin0.94.00.zip) is outdated which dates back to Jan 18 while the commit was from Feb 19.

Happy to help,
Thanks

**Comment by mahee96** [comment]
As mentioned above the **latest master branch already has the fix** and it has been tested with NPP v7.8.9 both x86, x64. 

Closing the issue
