### ISSUE TITLE
sync comments and constants

### ISSUE THREAD

**Issue by kbilsted** [kbilsted/NotepadPlusPlusPluginPack.Net#6]
sync all comments and constants from https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/scintilla/include/Scintilla.iface to  https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/master/Visual%20Studio%20Project%20Template%20C%23/Integration/Scintilla_iface.cs

work must be done on branch `topic/sync_scintillaiface` see https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/tree/topic/sync_scintillaiface

**Comment by dail8859** [comment]
Just FYI in case you know (or want to learn) Python, there are [Python scripts](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/287ce9ec147d6d64224d8990f99385f57a240df4/scintilla/scripts) that parse out the iface file. Shouldn't be too hard to make it auto-generate at least most of the Scintilla_iface.cs file.

**Comment by kbilsted** [comment]
hmm that might be a good approach. but some functions are not mapped, and I see the file has been changed 3 times since 2013 - so doing this manually may not be that much of a deal.,,
