### ISSUE TITLE
is not compatible with the current version notepad++

### ISSUE THREAD

**Issue by RobinGut999** [kbilsted/NotepadPlusPlusPluginPack.Net#80]
Hi Compiled your plugin template but it throws an error? what could be the problem?

```
Failed to load
is not compatible with the current version notepad++
```

![image](https://user-images.githubusercontent.com/81331618/122630001-14bb0b00-d0c1-11eb-85fe-48b7425efe6a.png)

**Comment by danwca** [comment]
see https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/issues/79#issue-922126396, for your reference.

**Comment by mahee96** [comment]
@RobinGut999 seems like a unicode translation issue for UTF chars wider than 16-bit maybe, causing incompatible plugin issue. Have to check with notepad++ and current plugin configs whether they match.

**Comment by mahee96** [comment]
This will be fixed in new releases, please do checkout the "releases" tab.
