### ISSUE TITLE
Create an editor gateway

### ISSUE THREAD

**Issue by kbilsted** [kbilsted/NotepadPlusPlusPluginPack.Net#9]
Create a primary interface for plugin-writers to Notepad++/Scintilla. 

changes must be done on branch topic/editorgateway_v1

**Comment by kbilsted** [comment]
@dail8859  looking at the stuff I've done so far with the gateway `EditorGateway.cs` I believe we can tweak the python script you PR'ed to code generate the same stuff for us - perhaps with the exception of `EditorAppendTextAndMoveCursor` and such convenience methods .. what is your gut feeling? I'll probably look into this in the comming days...

**Comment by dail8859** [comment]
Yeah it doesn't look too hard since a lot of it will just be [boilerplate](https://en.wikipedia.org/wiki/Boilerplate_code) code. If you aren't that familiar with Python or run into problems, let me know and I can take a crack at it.

**Comment by kbilsted** [comment]
Oh I've done a fair amount back in 2006 :)
Den 29. apr. 2016 23.02 skrev "dail8859" <notifications@github.com>:

**Comment by kbilsted** [comment]
@dail8859  I'm making great progress as you can see. However, I'm worried that when you look at the rewrite of demo.cs in 8b74f9260db0b5860c624db282e9e93016772af6 

	- Win32.SendMessage(hCurrentEditView, SciMsg.SCI_BEGINUNDOACTION, 0, 0);
	- Win32.SendMessage(hCurrentEditView, SciMsg.SCI_REPLACESEL, 0, insertString);
	- Win32.SendMessage(hCurrentEditView, SciMsg.SCI_SETSEL, currentPos, currentPos);
	- Win32.SendMessage(hCurrentEditView, SciMsg.SCI_ENDUNDOACTION, 0, 0);
	+ gateway.BeginUndoAction();
	+ gateway.ReplaceSel(insertString.ToString());
	+ gateway.SetSel(pos, pos);
	+ gateway.EndUndoAction();

that we are now introducing a lot of calls to `PluginBase.GetCurrentScintilla()` and I haven't dug into whether this being an issue.

Also I've added 

	[DllImport("user32")]
	public static extern IntPtr SendMessage(IntPtr hWnd, SciMsg Msg, IntPtr wParam, IntPtr lParam);
	[DllImport("user32")]
	public static extern IntPtr SendMessage(IntPtr hWnd, SciMsg Msg, IntPtr wParam, int lParam);


not sure if it works - but was required for making my code generation work (as it uses only utf-8 strings). This I have also yet to test

Also you will see in `cs.py` a lot of currently unsupported types. Please tell me if you want to deal with any of these. I'll keep you posted in here whenever I work on some of those types if you are interested in helping out so we don't do any double work.

feel free to comment/change the style of the python code or the generated code! I'll try not to rebase it any more if you want to PR ;)

**Comment by sanastasiou** [comment]
@kbilsted  There shouldn't be any problems with this call, unless of course u have some for loop doing this call and in the meantime someone changes the focused view. Bare in mind that any SendMessage call is asynchronous, thousand of such call / second will cause the message queue to congest..

There's the "direct" api which you could theoretically use, but I have run into trouble using it ( random crashes ) with no way to debug them.. So I guess it should be fine.

**Comment by dail8859** [comment]
> I'm worried that ... we are now introducing a lot of calls to `PluginBase.GetCurrentScintilla()`

Is the worry more of a performance issue or some other reason?

> Also I've added ... not sure if it works - but was required for making my code generation work.

I know for the straight C usage of SendMessage() there is a lot of casting data types. I'm not familiar enough with C# to know what the best way to handle this case would be.

> Also you will see in cs.py a lot of currently unsupported types.

First of all, I noticed `colour` is within `isTypeUnsupported()` however it is handled in `translateType()`. Is this correct?

> Please tell me if you want to deal with any of these.

Don't let me hold you back so work on whatever you like. If I find time before too long I may look into it a bit. I've done very little C# and especially haven't dealt with alot of this low level stuff in C# :)

**Comment by kbilsted** [comment]
@dail8859 

1. Yes my worries was performance.. since the old democode stored in a variable the current view.

2. unsupported types: Yeah I started supporting Color but then I figured I needded to read up on the representation as 3 values are stored in 1 int... feel free to help out on this. I'm currently working on the `resultstring`

**Comment by kbilsted** [comment]
@sanastasiou  Many thanks for the feedback.

**Comment by dail8859** [comment]
I wouldn't be too concerned about performance. Although it's hard to tell what all someone might build from this template.

One thing that might be possible is to catch the `NPPN_BUFFERACTIVATED` notification and cache the current view at that time. Haven't tried that myself but in theory that should be sufficient.

**Comment by sanastasiou** [comment]
Yeah you will need to observer buffer activated event definitely for MANY operations. I have some class in my plugin which does that.

**Comment by kbilsted** [comment]
@sanastasiou  @dail8859   but I'm thinking that it is bad to loose the kind of control you have with the low-level win32 api calls today. So I'm thinking the constructor of the ScintillaGateway should take the instance PluginBase.GetCurrentScintilla() - then we can mimic how things are today.

if a plugin is writing to some file and the user switches to another file/viwq, I would want the plugin to keep writing to the old file and not the file in focus. And if I want to have the functionality as the current ScintillaGateway I can always instantiate an object on each call.

@sanastasiou what observer classes should I be looking into.

**Comment by dail8859** [comment]
What I've done in my LuaScript plugin (which is the same way the PythonScript plugin does it) is have 3 "gateways". 

- `editor` - always refers to the "active" Scintilla instance, which is the way it does currently. The same method I mentioned of caching the current handle could be done.
- `editor1` - always refers to the "first" Scintilla instance.
- `editor2` - always refers to the "second" Scintilla instance.

Since normally the plugin just wants the current instance, it can just use `editor`. However in a case were you want to make sure you are using a specific Scintilla instance you can use `editor1` or `editor2`.

**Comment by kbilsted** [comment]
@dail8859  you are more than welcome to instantiate three instances in the project template `main.cs` file with comments explaining when to use what :+1:

**Comment by dail8859** [comment]
I don't have access to VS2015 at all and haven't done C# development in a while. 

An alternative solution would just be to let the user of the template handle all this kind of functionality. If they want to cache which Scintilla instance is the current one or just use something a bit simpler which always requests the current one for every call.

I guess it's a matter of how much the template does itself, or leaves it up to the user to do. Doesn't really matter either way.

**Comment by kbilsted** [comment]
@dail8859  yes the user should handle this himself, but I wanted the demo to reflect the best practises and the basis understanding needed in order to make a plugin...

**Comment by dail8859** [comment]
Ah. I see what you mean.

**Comment by kbilsted** [comment]
@dail8859  my knowledge of plugin writing is still limited. So for now it wont be added to the demo. 

btw did you see https://sourceforge.net/p/scintilla/feature-requests/1147/  I'm amazed to be the first to notice. also https://sourceforge.net/p/scintilla/bugs/1829/

**Comment by dail8859** [comment]
I did see the bug report and the fix for it. The feature request is a good idea.
